### ISSUE TITLE
Learned samples in each step K

### ISSUE THREAD

**Issue by mskl** [VICO-UoE/DatasetCondensation#1]
Hey, great paper! I'm just curious, do you have the synthetic data (or performance) from each step of K? I would expect that in each step, after the weights are resampled, that in early iterations the gradients look really different from later batches (steps T). I'm surprised that the data isn't completely changed after each resample. Thanks!

**Comment by PatrickZH** [comment]
Hi, thanks! You can set the interval of k, i.e. eval_it_pool in the code, to save and visualize the intermediate synthetic data. 
The synthetic data are optimized by the minimizing the matching loss of real and synthetic gradients. Although the gradients at early steps (t) distinctly differ from those at later steps in each training iteration (k), the matching loss of real and synthetic gradients at any step (t) will decrease and converge along with more training iterations (k). That’s why the synthetic data can converge in the training.
