### ISSUE TITLE
Can I have more images?

### ISSUE THREAD

**Issue by EchizenG** [VICO-UoE/DatasetCondensation#10]
I notice that you limit the ipc in get_loops function. Can I set it as 100, 1000 or even more? You mentioned that 'The following values are empirically good'. I just want to know how bad if ipc=100 or 1000. Thank you!

**Comment by PatrickZH** [comment]
Hi, of cause you can set ipc = 100 or 1000 for generating 100 or 1000 images per class. Then, you need to search good hyper-parameters - outer_loop and inner_loop for the two learning settings. Thank you!

**Comment by EchizenG** [comment]
Got it! Thank you!
