### ISSUE TITLE
About the reported performances of DM

### ISSUE THREAD

**Issue by SJShin-AI** [VICO-UoE/DatasetCondensation#12]
Your generously provided code helps me a lot for implementing new thang from existing methods.
Having said that, existing code do not show the reported performances of DM, even when i reproduced it with same hyper-parameters.
In detail, results for CIFAR10 with 50 samples per classes does not go over 55% even when i try bunch of hyper-parameter tunings.

**Comment by PatrickZH** [comment]
Hi, I have run the code one more time on a new environment just now. It achieves the reported result on 50 ipc CIFAR10.
