### ISSUE TITLE
Generate condensed images from file.pt

### ISSUE THREAD

**Issue by tranleanh** [VICO-UoE/DatasetCondensation#13]
Hi VICO-UoE,

Nice work!

I have tried the code and the training works so well.

But may I ask how to extract the generated images from the .pt file?

Thanks in advance!

**Comment by PatrickZH** [comment]
Hi, thanks! 
You can use the code at https://github.com/VICO-UoE/DatasetCondensation/blob/db516057ab92bab4ea50bad0811e7f059b019b79/main.py#L136
to first load the pt file, then do de-normalization, and save as png files.

**Comment by tranleanh** [comment]
Thanks a lot! 👍

**Comment by tranleanh** [comment]
Hi @PatrickZH,

Again, thanks for your response!

I read the code and the code line that you have shown me.

But it's not what I mentioned actually.

What I am wondering is how can we obtain the synthetic images (condensed images) by using the pt files which were provided in the [Google Drive](https://drive.google.com/drive/folders/1Dp6V6RvhJQPsB-2uZCwdlHXf1iJ9Wb_g?usp=sharing)?

**Comment by tranleanh** [comment]
I have found the solution.

Thanks!

**Comment by omarr12229** [comment]
@tranleanh could you mention the solution you found? 
TIA
