### ISSUE TITLE
Question about condensed data for continual learning

### ISSUE THREAD

**Issue by chunfuchen** [VICO-UoE/DatasetCondensation#17]
Thanks for sharing the codes and it is an amazing work. 

May I ask a question about the experiments for the paper Dataset Condensation with Distribution Match?
More specifically how do you condense the dataset at each step for continual learning.

Take the 5-step one as an example, for cifar100, each step contains 20 new classes and the images per class is 20, so each step you have 400 images in total. Then, my question is what is the set you used to condense on into these 400 images? Is it the original 10,000 images for the same 20 classes? (for cifar100, there are 500 training images per class)?

Or you did in another way? If so, do you mind elaborating on this. 

Thanks.

**Comment by PatrickZH** [comment]
Hi, thanks for the question. In this example, for each step, I will condense the original 20x500 images of the 20 new classes into 20x20 new synthetic images. Then, the 20x20 new synthetic images will be used together with old synthetic images (i.e. memory) to train the model. DM method can be used to condense images of each class independently.

**Comment by chunfuchen** [comment]
Thanks for your reply. That is very clear.
