### ISSUE TITLE
hyperparameters for CIFAR100

### ISSUE THREAD

**Issue by hjson1022** [VICO-UoE/DatasetCondensation#18]
Hi
It is nice work!
I want to know hyperparameters or any other settings for learning CIFAR100.
In DM paper, I saw you generated 20 images/class on CIFAR100 for continual learning.
I will try to generate synthetic images (20 images/class on CIFAR100) using DC method.
Thanks.

**Comment by PatrickZH** [comment]
You can simply set --ipc 20, then the algorithm will use the default hyper-parameters for DC/DSA. 

[    elif ipc == 20:](https://github.com/VICO-UoE/DatasetCondensation/blob/eabcb501df57c269e6edeede75e2f0a34e0eebac/utils.py#L282)
