### ISSUE TITLE
Hyperparams for large synthetic sets

### ISSUE THREAD

**Issue by pdejorge** [VICO-UoE/DatasetCondensation#2]
Congratulations on this interesting work. It seems that in the code you define the hyperparams only for the dataset sizes that appear in the paper (up to 50 ipc), would it be possible to provide the hyperparams for the results reported in your ICLR comments to reviewers? (with 100, 200, 500, 1000 condensed images per class).

Thank you in advance!

**Comment by PatrickZH** [comment]
Thank you for being interested in our paper. 
As you see, the corresponding hyper-parameters have been given for these results (≤ 50 images/class) presented in the paper. For extra experiments with > 50 images/class, we pick the best one of “outer_loop, inner_loop = 50, 10” and “outer_loop, inner_loop = 20, 25” for different settings. You may find the better combinations if you try more. Besides, we find that initializing synthetic images from random real images will benefit the performance when learning many images. So, we do it when learning many images.

**Comment by PatrickZH** [comment]
For 100 img/cls learning on CIFAR10, if you try "outer_loop, inner_loop = 100, 2", you may get 66.7% (DSA).
