### ISSUE TITLE
k-center baseline results

### ISSUE THREAD

**Issue by royson** [VICO-UoE/DatasetCondensation#21]
hi! thanks for your awesome works thus far in DC.
I am trying to replicate the reported k-center baseline results in the paper and was wondering if you could point me to the code base/pseudocode which you used.

**Comment by PatrickZH** [comment]
Hi, this is the pseudocode for k-center algorithm. You need to run it class by class.

```
mean = torch.mean(feature, dim=0, keepdim=True)
dis = distance(feature, mean)[:,0]
rank = torch.argsort(dis) 
idx_centers = rank[:1].tolist() 
for i in range(ipc-1):
    feature_centers = feature[idx_centers]
    dis_center = distance(feature, feature_centers)
    dis_min, _ = torch.min(dis_center, dim=-1)
    id_max = torch.argmax(dis_min).item()
    idx_centers.append(id_max)
```
