### ISSUE TITLE
Why your train acc always be 1.0?

### ISSUE THREAD

**Issue by HiccupRL** [VICO-UoE/DatasetCondensation#24]
![image](https://user-images.githubusercontent.com/100175107/232661100-6e15b54d-50e0-49ef-a2f6-0775bc7e481d.png)

**Comment by HiccupRL** [comment]
I just simply git your code and use the command `python main.py  --dataset CIFAR10  --model ConvNet  --ipc 1`.

**Comment by PatrickZH** [comment]
Since the ipc = 1, it is easy to obtain 100% train accuracy on the only 10 training images in 300 epochs.

**Comment by HiccupRL** [comment]
Oh, get this. Thank you for your kind answering.

**Comment by hailuu684** [comment]
Hello, I tried ipc=50 and train acc still = 1.0
