### ISSUE TITLE
DM Synthesized Images

### ISSUE THREAD

**Issue by paganpasta** [VICO-UoE/DatasetCondensation#29]
Hi,

Thanks for putting together this amazing project. I found the shared syn datasets very useful! 
Do you plan to add DM generated syn images to the shared folder any time in the future ?

Thanks!

**Comment by PatrickZH** [comment]
Hi, I just uploaded some DM synthetic images [here](https://drive.google.com/drive/folders/1Dp6V6RvhJQPsB-2uZCwdlHXf1iJ9Wb_g?usp=sharing).

**Comment by paganpasta** [comment]
Thank you for the quick response.  Any chance I can get ipc-{1,10} for the same 2 setup that you uploaded?

**Comment by PatrickZH** [comment]
Sorry, you may need to run the code to synthesize it by yourselef.
