### ISSUE TITLE
Use the code for other dataset for multioutput classification task

### ISSUE THREAD

**Issue by MarioAvolio** [VICO-UoE/DatasetCondensation#33]
Hello,

I hope this message finds you well. I am currently working on a project involving multioutput classification, and I am interested in using your code (specifically the part related to dataset distillation) for my task. However, I have a few questions and clarifications I would like to seek your guidance on.

I am aiming to apply dataset distillation techniques to MAAD_FACE dataset for a multioutput classification task. Your repository has been a great resource, and I believe your code could significantly enhance the performance of my model. 

Thank you for your time and assistance. I look forward to your guidance and suggestions on this matter.

Best regards,

**Comment by PatrickZH** [comment]
Hi, Thanks for your interest in our code. If you can specify your problems about the code, I would try to help you. Thanks.
