### ISSUE TITLE
Could you please release the synthetic Cifar10

### ISSUE THREAD

**Issue by taoyang1122** [VICO-UoE/DatasetCondensation#4]
Hi, thanks for the great work. Could you please release the synthetic Cifar10 trained on ConvNet or ResNet-18, with 10/50 imgs/class? This would be greatful since I was trying to use the synthetic data to conduct some downstream tasks. Thanks.

**Comment by PatrickZH** [comment]
Hi, thanks for your interest in our work. I have uploaded some synthetic sets in Google Drive. Please refer to readme.md.

**Comment by taoyang1122** [comment]
Hi, thanks for your reply, that's really helpful!
