### ISSUE TITLE
Instructions to replicate the graph related to continual learning experiments 

### ISSUE THREAD

**Issue by bhattg** [VICO-UoE/DatasetCondensation#7]
Hello, 

I was wondering if there is a script that can be run to replicate the results related to the Continual Learning experiments. 

Thanks for the awesome paper!

**Comment by PatrickZH** [comment]
Hi,

Thank you for being interested in our work.

Currently, we don't plan to provide more codes for other experiments now. You can refer to my previous GitHub repository https://github.com/PatrickZH/End-to-End-Incremental-Learning for continual learning implementation. Thank you!
